student_network/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('myusers.urls', namespace = 'users')),
    url(r'^topics/', include('topics.urls', namespace = 'topics')),
    url(r'^resources/', include('resources.urls', namespace = 'resources')),
    url(r'^$', include('userhome.urls', namespace = 'userhome')),
    url(r'^activities/', include('activities.urls', namespace = 'activities')),
]

student_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('myusers.urls', namespace = 'users')),
    url(r'^topics/', include('topics.urls', namespace = 'topics')),
    url(r'^resources/', include('resources.urls', namespace = 'resources')),
    url(r'^$', include('userhome.urls', namespace = 'userhome')),
    url(r'^activities/', include('activities.urls', namespace = 'activities')),
]

topics/urls.py
from django.conf.urls import url
from . import views

# Topics URLs
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create', views.create, name='create'),
    url(r'^delete/(?P<topic_id>[0-9]+)/', views.delete, name='delete'),
    url(r'^topics_created', views.topics_created, name='topics_created'),
    url(r'^(?P<topic_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^follow_topic/$', views.my_follow, name='my_follow'),
    url(r'^unfollow_topic/$', views.my_unfollow, name='my_unfollow'),
    url(r'^following/$', views.my_following, name='my_following'),
]

userhome/urls.py
from django.conf.urls import url
from . import views
# Topic URL
urlpatterns = [
    url(r'^$', views.home, name='home'),
]

topics/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    """
    Topic model with defined fields
    """
    topic_name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now = False, auto_now_add = True)
    description = models.TextField()
    user = models.ForeignKey(User,null=True) 
    
    def get_fields(self):
        """
        Return all the fields the for a topic instance.
        """    
        fields = [self.topic_name, self.description]
        return fields

    def __str__(self):
        return self.topic_name

topics/forms.py
from django import forms
from .models import Topic

class TopicForm(forms.ModelForm):
    """
    Form to add a topic
    """
    topic_name = forms.CharField(label='Topic Name',required=True)
    description = forms.CharField(label='Description',widget=forms.Textarea,required=True)
  
    class Meta:
        """
        Model used in the form
        """
        model = Topic
        fields = ['topic_name', 'description']


    def clean_topic_name(self):
        """
        Perform check in the topic name of the instance
        """
        topic_name = self.cleaned_data['topic_name']
        if (Topic.objects.filter(topic_name=topic_name).exists()):
            # check if topic name already exists
            raise forms.ValidationError("Topic Name already exists!")
        return topic_name

    def __init__(self, *args, **kwargs):
        super(TopicForm, self).__init__(*args, **kwargs)
        # set the errors for the fields in the form
        for field in self.fields.values():
            field.error_messages = {'required':'The field {fieldname} is required'.format(
                fieldname=field.label)}

topics/views.py
from .forms import TopicForm
from .models import Topic
from django.shortcuts import render
from django.http import Http404, HttpResponse
from django.contrib.auth.models import User, Group
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponseBadRequest, Http404
from actstream.actions import follow, unfollow
from actstream.models import following, followers
from actstream import action
from resources.models import Resource

# Topics views

def index(request):
    """
    This handles the index of the topics existing returns a template with all 
    the topics and the ones the request user follows.
    """
    # check whether user is authenticated
    if request.user.is_authenticated():

        topics_list = Topic.objects.order_by('topic_name')
        # topics the user is following using the actstream following function
        following_list=  following(request.user) 

        context = {
            "topics_list":topics_list,
            "following_list":following_list,
        }
    else:
        topics_list = Topic.objects.order_by('topic_name')
        context = {
            "topics_list":topics_list,
        }

    template = 'topics/index.html'

    return render(request, template, context)


def detail(request, topic_id):
    """
    Check all the details for a topic with topic_id including the resources 
    added to it.
    """
    try:
        topic = Topic.objects.get(pk=topic_id)
        topic_resources = Resource.objects.filter(topic_id=topic_id)
    except Topic.DoesNotExist:
        raise Http404("ID not found")

    context ={
        "topic":topic,
        "topic_resources":topic_resources
    }
    template = 'topics/detail.html'

    return render(request, template, context)

# login required to created a topic
@login_required(login_url = '/users/login')
def create(request):
    """
    Create a topic 
    """
    #form where topic is created
    form = TopicForm(request.POST or None)

    if form.is_valid():
        instance = form.save(commit=False)
        # check whether the topic name already exist 
        topic_exist = \
                (Topic.objects.filter(topic_name=instance.topic_name).exists())
        if not topic_exist:
            # If topic does not exist then create it
            instance.user_id = request.user.id
            instance.save()
            template = 'topics/create_success.html'
            # record the action performed a create action with the request user 
            # and a topic instance
            action.send(request.user, verb='created',target=instance)
            return render(request,template)            
    else:
        
        template = 'topics/create.html'
        context = {
            "form":form,
        }

        return render(request, template, context)


def topics_created(request):
    """
    Retrieves the topics created by the user who is making the request
    """
    user_id = request.user.id
    # In the topic model filter the ones with user_id
    topics_created = Topic.objects.filter(user_id=user_id)
    template="topics/topics_created.html"
    context={
        "topics_created":topics_created
    }

    return render(request,template,context)


def delete(request, topic_id):
    """
    Delete a topic by its ID
    """
    instance = Topic.objects.get(id=topic_id)
    instance.delete()
    template = "topics/delete_success.html"
    return render(request, template)

def my_follow(request):
    """ 
    Uses the follow function from the actstream library this takes an user 
    request and a topic by its ID and creates the follow relationship between
    user and topic.
    Returns a template with the successful action
    """
    if request.method == 'GET':        
        topic_id = request.GET.get('topic_id') #get topic id from the request
        if topic_id:
            topic_to_follow = Topic.objects.get(pk=topic_id)
            #user who makes the request
            req_user = User.objects.get(username=request.user) 
            #template to be rendered 
            template = 'topics/follow_success.html'
            follow(req_user, topic_to_follow, actor_only=False)
            return render(request, template)
        else:
            return HttpResponse("Follow cannot be processed")
    else:   
        return HttpResponse("Request cannot be processed")
    

def my_unfollow(request):
    """
    Use the unfollow from actstream to unfollow a topic 
    """
    if request.method == 'GET':        
        topic_id = request.GET.get('topic_id')
        if topic_id:
            topic_to_unfollow = Topic.objects.get(pk=topic_id)
            req_user = User.objects.get(username=request.user)        
            template = 'topics/unfollow_success.html'
            # user request to unfollow a topic 
            unfollow(req_user, topic_to_unfollow) 
            return render(request, template)
        else:
            return HttpResponse("Unfollow cannot be processed")

    else:
        return HttpResponse("Unfollow cannot be processed")


@login_required(login_url = '/users/login')
def my_following(request):
    """
    Render a list of the topics request user is currently following
    """
    following_list = []
    f_list=  following(request.user)
    for f in f_list:
        # check whether the topic still exists
        if f is not None:
            following_list.append(f)    
    template = "topics/following.html"
    context={
        "following_list":following_list,
    }
    return render(request, template, context)

templates/topics/create.html
{% extends "base.html" %}

{% block topic_create_content %}

<div class="section" id="create-topic-container">
<title>Create Topic</title>
<h1>Create Topic</h1>

{% if topic_exist %}

<p>Please use another name or click <a href="{% url 'topics:index' %}">here</a> to see topics available.</p>

{% endif %}

<form method='POST'>{% csrf_token %}
<div class="form-group">
	{% if form.topic_name.errors %}
	<div class="alert alert-danger" role="alert">
	<span class="sr-only">Error:</span>{{ form.topic_name.errors }}
		</div>
	{% endif %}
		<label>{{form.topic_name.label}}</label>
		<input class="form-control" id="id_topic_name" name="topic_name" type="text">

</div>
<div class="form-group">
	{% if form.description.errors %}
	<div class="alert alert-danger" role="alert">
	<span class="sr-only">Error:</span>{{ form.description.errors }}
		</div>
	{% endif %}
		<label for="id_description">Description:</label> 
		<textarea class="form-control" cols="40" id="id_description" name="description" rows="10"></textarea>
</div>
	<input class="btn btn-lg btn-primary" type='submit' value="Create"/>
</form>
</div>

{% endblock %}

templates/topics/create_success.html
{% extends "base.html" %}

{% block create_successful_content %}
<div class="section">
	<h1><span class="label label-success">Created topic successfully</span></h1>
	<a href="{% url 'userhome:home' %}">Go back home</a>
</div>
{% endblock %}

templates/topics/delete_success.html
<h2><span class="label label-success">Delete successful</span></h2>

templates/topics/detail.html
{% extends "base.html" %}
{% block topic_detail_content %}
<div class="section">
	
<h1>{{ topic.topic_name }}</h1>
<ul>
	{% for field in topic.get_fields %}
    <li>{{ field }}</li>
	{% endfor %}
</ul>

<h1>Resources</h1>
{% if topic_resources %}
<ul>
	{% for resource in topic_resources %}
	<div class="panel panel-primary">
		<div class="panel-heading">
        	<h3 class="panel-title">Resource Name: {{resource.resource_name}}</h3>
     	</div>
     	<div class="panel-body">
     		<div class="panel panel-default">

				<div class="panel-heading"><h3 class="panel-title">Resource Type</h3></div>
				<div class="panel-body">{{resource.resource_type}}</div>

      			<div class="panel-heading"><h3 class="panel-title">Link</h3></div>
     			<div class="panel-body"><a href="{{resource.url}}">Link of {{resource.resource_name}}</a></div>

				<div class="panel-heading"><h3 class="panel-title">Description</h3></div>
     			<div class="panel-body">{{resource.description}}</div>

     			<div class="panel-heading"><h3 class="panel-title">Date Added</h3></div>
     			<div class="panel-body">{{resource.created_at}}</div>

			</div>
      	</div>
	</div>

	{% endfor %}
</ul>
{% else %}
<h2><span class="label label-info">This topic has no resources</span></h2>
{% endif %}
</div>

{% endblock %}

<div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Panel title</h3>
      </div>
      <div class="panel-body">
        Panel content
      </div>
    </div>

templates/topics/follow_success.html
<p>Follow Success</p>

templates/topics/following.html
{% extends "base.html" %}
{% load staticfiles %}

{% block following_content %}
<div class="section" id="following-container">
	<h2>Following</h2>
	{% if following_list %}
	<ol>
		{% for topic in following_list %}
		<li>
			<a href="{% url 'topics:detail' topic.id%}">{{ topic.topic_name }}</a>
		</li>
			<button class="btn btn-sm btn-default add-resource" id= "add-resource-btn-{{topic.id}}" data-topicid="{{ topic.id }}">Add Resource</button>	

		<div class="reply-resource-form" id="resource-form-{{topic.id}}"></div>

		{% endfor %}

	</ol>
	{% else %}
	<div class="alert alert-info" role="alert">
		<strong>You are currently not following any topic!</strong>
		<br>
		<strong>Start following <a href="{% url 'topics:index' %}">here</a>!</strong>

	</div>

	{% endif %}
</div>

{% endblock %}

templates/topics/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block index_content%}
	{% if topics_list %}
	<ul>
	{% for topic in topics_list%}
	<div class="section" id="topic-index-container">
		<li id="index-topic-name" ><a href="{% url 'topics:detail' topic.id %}">{{ topic.topic_name }}</a></li>
		<p id="index-topic-description">Description: {{ topic.description }}</p>
		{% if user.is_authenticated and topic in following_list%}
		<button class="btn followButton following" data-topicid="{{ topic.id }}">Following</button>	
		{% elif user.is_authenticated %}
		<button class="btn followButton" data-topicid="{{ topic.id }}">Follow</button>
		{% endif %}
	</div>
	{% endfor %}
	</ul>
	{% else %}
	<div class="section" id="topic-index-container">
	<h2>topics</h2>
		<div class="alert alert-info" role="alert">
			<strong>No topics available!</strong>
			<br>
			<strong>Add a new topic <a href="{% url 'topics:create' %}">here</a>!</strong>
		</div>
	</div>
	{% endif %}	
{% endblock %}

templates/topics/topics_created.html
{% extends "base.html" %}
{% block topics_created_content%}
<div class="section" id="following-container">
	<h2>My Topics</h2>
	{% if topics_created %}
	<ol>
		{% for topic in topics_created %}
		<div id="topic-{{topic.id}}">
			<li>
				<a href="{% url 'topics:detail' topic.id%}">{{ topic.topic_name }}</a>
			</li>
				<button class="btn btn btn-sm btn-default add-resource" id= "add-resource-btn-{{topic.id}}" data-topicid="{{ topic.id }}">Add Resource</button>
				<button class="btn btn-sm btn-primary delete-topic" id= "delete-topic-btn-{{topic.id}}" data-topicid="{{ topic.id }}">Delete Topic</button>		
			<div id="resource-form-{{topic.id}}"></div>
		</div>
		{% endfor %}

	</ol>
	{% else %}
	<p>You have no topics.</p>
	<p>Create one!</p>
	{% endif %}
</div>
{% endblock %}