student_network/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('myusers.urls', namespace = 'users')),
    url(r'^topics/', include('topics.urls', namespace = 'topics')),
    url(r'^resources/', include('resources.urls', namespace = 'resources')),
    url(r'^$', include('userhome.urls', namespace = 'userhome')),
    url(r'^activities/', include('activities.urls', namespace = 'activities')),
]

student_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('myusers.urls', namespace = 'users')),
    url(r'^topics/', include('topics.urls', namespace = 'topics')),
    url(r'^resources/', include('resources.urls', namespace = 'resources')),
    url(r'^$', include('userhome.urls', namespace = 'userhome')),
    url(r'^activities/', include('activities.urls', namespace = 'activities')),
]

topics/urls.py
from django.conf.urls import url
from . import views

# Topics URLs
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create', views.create, name='create'),
    url(r'^delete/(?P<topic_id>[0-9]+)/', views.delete, name='delete'),
    url(r'^topics_created', views.topics_created, name='topics_created'),
    url(r'^(?P<topic_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^follow_topic/$', views.my_follow, name='my_follow'),
    url(r'^unfollow_topic/$', views.my_unfollow, name='my_unfollow'),
    url(r'^following/$', views.my_following, name='my_following'),
]

resources/models.py
from django.db import models
from topics.models import Topic
from django.contrib.auth.models import User


class Resource(models.Model):
    """
    Resource model with defined fields
    """
    resource_name = models.CharField(max_length=100)
    url = models.URLField()
    description = models.TextField()
    resource_type = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now = False, auto_now_add = True)
    user = models.ForeignKey(User) 
    topic = models.ForeignKey(Topic)
    

    
    def get_fields(self):
        """
        Return all the fields the for a resource instance.
        """
        # set the errors for the fields in the form
        fields = [self.resource_name, self.url, self.description, self.resource_type, self.user]
        return fields

    def __str__(self):
        return self.resource_name

resources/forms.py
from django import forms
from .models import Resource


class AddResourceForm(forms.ModelForm):
	"""
	Form to add a resource
	"""
	url = forms.URLField(label='Link',required=True)
	resource_type = forms.CharField(label='Type',max_length=100)

	class Meta:
		"""
		Model used in the form
		"""
		model = Resource
		fields = ['resource_name', 'url', 'description', 'resource_type']

	def __init__(self, *args, **kwargs):
		super(AddResourceForm, self).__init__(*args, **kwargs)

		# set the errors for the fields in the form
		for field in self.fields.values():
			field.error_messages = {'required':'The field {fieldname} is required'.format(
				fieldname=field.label)}

topics/forms.py
from django import forms
from .models import Topic

class TopicForm(forms.ModelForm):
    """
    Form to add a topic
    """
    topic_name = forms.CharField(label='Topic Name',required=True)
    description = forms.CharField(label='Description',widget=forms.Textarea,required=True)
  
    class Meta:
        """
        Model used in the form
        """
        model = Topic
        fields = ['topic_name', 'description']


    def clean_topic_name(self):
        """
        Perform check in the topic name of the instance
        """
        topic_name = self.cleaned_data['topic_name']
        if (Topic.objects.filter(topic_name=topic_name).exists()):
            # check if topic name already exists
            raise forms.ValidationError("Topic Name already exists!")
        return topic_name

    def __init__(self, *args, **kwargs):
        super(TopicForm, self).__init__(*args, **kwargs)
        # set the errors for the fields in the form
        for field in self.fields.values():
            field.error_messages = {'required':'The field {fieldname} is required'.format(
                fieldname=field.label)}

templates/resources/add-resource-form.html
{% load staticfiles %}

<form method="post" id="form-{{following_topic.id}}" action="/resources/add_resource/{{following_topic.id}}/">{% csrf_token %}
  <div class="form-group">
    {% if form.resource_type.errors %}
    <div class="alert alert-danger" role="alert">
       <span class="sr-only">Error:</span>
        {{ form.resource_type.errors }}
      </div>
      {% endif %}
      <label>{{form.resource_type.label}}</label>
      <input class="form-control" id="id_resource_type" name="resource_type" type="resource_type" placeholder="Resource type (e.g. Photo, article, paper, etc.)">
    </div>
    <div class="form-group">
      {% if form.resource_name.errors %}
      <div class="alert alert-danger" role="alert">
        <span class="sr-only">Error:</span>
        {{ form.resource_name.errors }}
      </div>
      {% endif %}
      <label>Resource Name</label>
      <input class="form-control" id="id_resource_name" name="resource_name" type="resource_name" placeholder="Name of the resource (e.g. Title, Journal)">
    </div>
    <div class="form-group">
      {% if form.url.errors %}
      <div class="alert alert-danger" role="alert">
        <span class="sr-only">Error:</span>
        {{ form.url.errors }}
        </div>
      {% endif %}
      <label>Link</label>
      <input class="form-control" id="id_url" name="url" type="url" placeholder='Link where the resource can be found'>
     </div>
    <div class="form-group">
      {% if form.description.errors %}
      <div class="alert alert-danger" role="alert">
      <span class="sr-only">Error:</span>
      {{ form.description.errors }}
      </div>
      {% endif %}
      <label>Description</label>
      <input class="form-control" id="id_description" name="description" type="text" placeholder='Brief description of the resource (e.g. This is an article about ...)'>
    </div>     
    <input class="btn btn-default" id="add-submit-{{following_topic.id}}" data-topicid="{{following_topic.id}}" type='submit' value="Submit"/> 
  </form>

{% include 'javascript.html' %}

templates/resources/add-success.html
<h2><span class="label label-success">Add Successful</span></h2>