myusers/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login

# User URLs
urlpatterns = [
    url(r'^register/$',views.register, name = 'register'),
    url(r'^login/$', views.sign_in, name = 'login'),
    url(r'^logout', views.sign_out, name = 'logout'),
]

student_network/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('myusers.urls', namespace = 'users')),
    url(r'^topics/', include('topics.urls', namespace = 'topics')),
    url(r'^resources/', include('resources.urls', namespace = 'resources')),
    url(r'^$', include('userhome.urls', namespace = 'userhome')),
    url(r'^activities/', include('activities.urls', namespace = 'activities')),
]

student_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('myusers.urls', namespace = 'users')),
    url(r'^topics/', include('topics.urls', namespace = 'topics')),
    url(r'^resources/', include('resources.urls', namespace = 'resources')),
    url(r'^$', include('userhome.urls', namespace = 'userhome')),
    url(r'^activities/', include('activities.urls', namespace = 'activities')),
]

topics/urls.py
from django.conf.urls import url
from . import views

# Topics URLs
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create', views.create, name='create'),
    url(r'^delete/(?P<topic_id>[0-9]+)/', views.delete, name='delete'),
    url(r'^topics_created', views.topics_created, name='topics_created'),
    url(r'^(?P<topic_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^follow_topic/$', views.my_follow, name='my_follow'),
    url(r'^unfollow_topic/$', views.my_unfollow, name='my_unfollow'),
    url(r'^following/$', views.my_following, name='my_following'),
]

userhome/urls.py
from django.conf.urls import url
from . import views
# Topic URL
urlpatterns = [
    url(r'^$', views.home, name='home'),
]

templates/actions.html
<div class="sidebar" id="left-sidebar">
	<h3>MY TOPICS</h3>
	<ul class="list-group">
		<li class="list-group-item"><a href="{% url 'topics:create' %}"> Add a Topic </a></li>
		<li class="list-group-item"><a href="{% url 'topics:topics_created' %}"> Topics Created</a></li>
	</ul>
</div>

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en" hola_ext_inject="disabled">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <!-- Bootstrap core CSS -->
    <link href="{% static "css/student-network-bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/navbar-fixed-top.css" %}" rel="stylesheet">

  </head>

  <body>

    {% include 'navbar.html' %}

    {% block login_content %}{% endblock %}    
    {% block register_content%}{% endblock %}

    {% block home_content %}{% endblock %}

    {% block topic_create_content %}{% endblock %}
    {% block index_content%}{% endblock %}
    {% block topics_created_content%}{% endblock %}
    {% block topic_detail_content %}{% endblock %}

    {% block create_successful_content %}{% endblock %}
    {% block following_content %}{% endblock %}
    {% block add_resource_form_content %}{%endblock%}

    {% include 'javascript.html' %}

    </body>
</html>

templates/home.html
{% extends "base.html" %}

{% block home_content %}
	{% if user.is_authenticated %}
		{% include 'actions.html' %}
		{% include 'activities/recent.html' %}
	{% else %}
		<div class="section">
			<h1>Content not available to  unregistered users.</h1>	
		</div>
	{%  endif%}
{% endblock %}

templates/javascript.html
{% load staticfiles %}

<script src="{% static "js/jquery-1.11.3.js" %}"></script> 
<script src="{% static "js/topics-functions.js" %}"></script>
<script src="{% static "js/resources-functions.js" %}"></script>

templates/navbar.html
{% load staticfiles %}

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'userhome:home'%}">Student Network</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'topics:index' %}">Topics</a></li>
        <li><a href="{% url 'topics:my_following' %}">Following</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li class="active"><a href="">{{ user.username }}</a></li>
        <li><a href="{% url 'users:logout' %}">Log Out</a></li>
        {% else %}
        <li><a href="{% url 'users:register' %}">Register</a></li>
        <li><a href="{% url 'users:login' %}">Login</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>